import type { Metadata } from "next";
import {Mukta_Vaani} from "next/font/google";
import "./globals.css";
import Header from "./components/header/Header";

const mukta_vaani = Mukta_Vaani({
  weight : ["300", "400", "600", "700"],
  subsets: ['gujarati', 'latin', 'latin-ext']
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${mukta_vaani.className} max-w-[1200px] mx-auto`}>
          <Header />
          {children}
      </body>
    </html>
  );
}
